# Generated by Django 5.0.2 on 2024-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitcoinConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("value_per_bitcoin", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "bitcoin_conversion",
                "managed": False,
            },
        ),
    ]
