# Generated by Django 5.0.1 on 2024-03-23 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_faq"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="faq",
            table="Faq",
        ),
        migrations.AlterModelTable(
            name="query",
            table="Query",
        ),
    ]
